export const DISTANCE_DURATIONS = 'DISTANCE_DURATIONS';
export const FIND_CURRENT_LOCATION = 'FIND_CURRENT_LOCATION';
export const REORDER_BATHROOMS = 'REORDER_BATHROOMS';
export const ACTIVE_MARKER = 'ACTIVE_MARKER';
export const SHOW_INFO_WINDOW = 'SHOW_INFO_WINDOW';
export const SELECT_A_PLACE = 'SELECT_A_PLACE';
export const ADD_NEW_BATHROOM_LAT_LNG = 'ADD_NEW_BATHROOM_LAT_LNG';
